### ISSUE TITLE
Remove component flattening

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure-text-minimessage#156]
Now that Adventure has it's own alternative, we should remove MiniMessage's component flattening code completely.

For ease of use, we could provide the builder with an operator that touches each component at the end of the creation process which could be used to compact components (possibly by default?).

**Comment by rymiel** [comment]
(Apparently what adventure calls "flattening" isn't the same "flattening" as here and is actually "compacting").
I attempted to tackle this but was stopped by KyoriPowered/adventure#455 as it just happens to match the format that a lot of minimessage-parsed messages end up in. Also just asking if all the tests should be rewritten to match the new compacted output ~~because technically you can just also compact the test base~~
