### ISSUE TITLE
Look into making tag open/close characters configurable

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure-text-minimessage#182]
Possibly splitting it between tag and template . Perhaps with a predicate option?

**Comment by MiniDigger** [comment]
I don't think this should be a thing. MiniMessage should be a standard, something that is the same across all plugins, especially since it will be bundled into paper soon (tm)
I could see an argument to handle template differently (maybe some translation service requires a special format or stuff like that), but so far nobody really has complained so we should stick to the standard for now.
